//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makh.Timesheet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Makh.Timesheet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان اضافه کردن گروه در بالای گروه متفرقه و یا به عنوان فرزند آن وجود ندارد فقط می توان در پایین گروه متفرقه گروه اضافه کرد.
        /// </summary>
        internal static string AddingRestrictionOfMotafareqehGroup {
            get {
                return ResourceManager.GetString("AddingRestrictionOfMotafareqehGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا باید یک فایل پایگاه داده انتخاب شود سپس اتصال برسی گردد.
        /// </summary>
        internal static string DBFileIsNotSelected {
            get {
                return ResourceManager.GetString("DBFileIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل نمی تواند خالی باشد.
        /// </summary>
        internal static string FilenameCantBeNullOrEmpty {
            get {
                return ResourceManager.GetString("FilenameCantBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه نمی تواند خالی یا فاصله باشد.
        /// </summary>
        internal static string GroupNameCanntBeEmpty {
            get {
                return ResourceManager.GetString("GroupNameCanntBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه.
        /// </summary>
        internal static string GroupTitleColumnName {
            get {
                return ResourceManager.GetString("GroupTitleColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        internal static string GroupTitleColumnWidth {
            get {
                return ResourceManager.GetString("GroupTitleColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #005c99.
        /// </summary>
        internal static string HierarchyLevel01Color {
            get {
                return ResourceManager.GetString("HierarchyLevel01Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #006bb3.
        /// </summary>
        internal static string HierarchyLevel02Color {
            get {
                return ResourceManager.GetString("HierarchyLevel02Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #007acc.
        /// </summary>
        internal static string HierarchyLevel03Color {
            get {
                return ResourceManager.GetString("HierarchyLevel03Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #008ae6.
        /// </summary>
        internal static string HierarchyLevel04Color {
            get {
                return ResourceManager.GetString("HierarchyLevel04Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0099ff.
        /// </summary>
        internal static string HierarchyLevel05Color {
            get {
                return ResourceManager.GetString("HierarchyLevel05Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1aa3ff.
        /// </summary>
        internal static string HierarchyLevel06Color {
            get {
                return ResourceManager.GetString("HierarchyLevel06Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #33adff.
        /// </summary>
        internal static string HierarchyLevel07Color {
            get {
                return ResourceManager.GetString("HierarchyLevel07Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4db8ff.
        /// </summary>
        internal static string HierarchyLevel08Color {
            get {
                return ResourceManager.GetString("HierarchyLevel08Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #66c2ff.
        /// </summary>
        internal static string HierarchyLevel09Color {
            get {
                return ResourceManager.GetString("HierarchyLevel09Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #80ccff.
        /// </summary>
        internal static string HierarchyLevel10Color {
            get {
                return ResourceManager.GetString("HierarchyLevel10Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #99d6ff.
        /// </summary>
        internal static string HierarchyLevel11Color {
            get {
                return ResourceManager.GetString("HierarchyLevel11Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #b3e0ff.
        /// </summary>
        internal static string HierarchyLevel12Color {
            get {
                return ResourceManager.GetString("HierarchyLevel12Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ccebff.
        /// </summary>
        internal static string HierarchyLevel13Color {
            get {
                return ResourceManager.GetString("HierarchyLevel13Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e6f5ff.
        /// </summary>
        internal static string HierarchyLevel14Color {
            get {
                return ResourceManager.GetString("HierarchyLevel14Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        internal static string HierarchyLevel15Color {
            get {
                return ResourceManager.GetString("HierarchyLevel15Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        internal static string MsgBoxCaption {
            get {
                return ResourceManager.GetString("MsgBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای اضافه کردن گروه باید حداقل یک سطر را انتخاب شود و سپس گزینه مناسب جهت اضافه شدن گروه زده شود.
        /// </summary>
        internal static string NoRowSelected {
            get {
                return ResourceManager.GetString("NoRowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا، یک عنوان برای گروه جدید وارد کنید:.
        /// </summary>
        internal static string PlzTypeGroupName {
            get {
                return ResourceManager.GetString("PlzTypeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        internal static string RowNumberColumnName {
            get {
                return ResourceManager.GetString("RowNumberColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string RowNumberColumnWidth {
            get {
                return ResourceManager.GetString("RowNumberColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سرور و نام پایگاده داده وارد نشده است.
        /// </summary>
        internal static string ServerAndDatabaseIsNotEntered {
            get {
                return ResourceManager.GetString("ServerAndDatabaseIsNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال با موفقیت بررسی شد.
        /// </summary>
        internal static string TestConnectionSucceeded {
            get {
                return ResourceManager.GetString("TestConnectionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی دی کاربر و پسورد وارد نشده است.
        /// </summary>
        internal static string UserIDAndPasswordIsNotEntered {
            get {
                return ResourceManager.GetString("UserIDAndPasswordIsNotEntered", resourceCulture);
            }
        }
    }
}
